import { NextRequest, NextResponse } from "next/server";
import Fuse from "fuse.js";
import type { SearchIndexItem } from "@/lib/types";

// In production, this would be loaded from generated search index
const searchIndex: SearchIndexItem[] = [
  {
    id: "foundations/history-and-systems",
    title: "History & Systems of Psychology",
    description: "Explore the historical development of psychological thought from ancient philosophy to modern neuroscience.",
    domain: "foundations",
    domainTitle: "Foundations of Psychology",
    topic: "history-and-systems",
    keywords: ["history", "behaviorism", "psychoanalysis", "cognitive revolution", "Wundt", "James"],
    content: "Psychology as a scientific discipline. Wilhelm Wundt. Structuralism. Functionalism. Behaviorism. Cognitive revolution.",
    sections: ["Introduction", "Philosophical Foundations", "The Birth of Scientific Psychology", "Major Schools of Psychology", "The Cognitive Revolution", "Contemporary Integrative Approaches", "Historical Perspectives on Key Debates"],
    keyConcepts: ["Structuralism", "Functionalism", "Behaviorism", "Psychoanalysis", "Cognitive Revolution", "Dualism", "Introspection", "Operant Conditioning"],
    href: "/wiki/foundations/history-and-systems",
  },
  {
    id: "foundations/research-methods",
    title: "Research Methods & Statistics",
    description: "Learn the scientific methods used to study behavior and mental processes.",
    domain: "foundations",
    domainTitle: "Foundations of Psychology",
    topic: "research-methods",
    keywords: ["research", "statistics", "experiment", "correlation", "validity", "reliability"],
    content: "Scientific method. Experimental research. Correlational studies. Descriptive research. Statistical analysis.",
    sections: ["Introduction", "Research Methods Overview", "Experimental Design", "Statistical Analysis", "Validity and Reliability"],
    keyConcepts: ["Variable", "Hypothesis", "Random Assignment", "Internal Validity", "External Validity", "Confounding Variable", "Control Group"],
    href: "/wiki/foundations/research-methods",
  },
  {
    id: "foundations/ethics",
    title: "Ethics in Psychological Research",
    description: "Understand the ethical guidelines that govern psychological research and practice.",
    domain: "foundations",
    domainTitle: "Foundations of Psychology",
    topic: "ethics",
    keywords: ["ethics", "informed consent", "IRB", "Belmont Report", "APA"],
    content: "Ethical guidelines. Informed consent. Belmont Report. APA Ethics Code. Institutional Review Boards.",
    sections: ["Introduction", "Ethical Principles", "Informed Consent", "Protection from Harm", "Deception", "Ethics Committees"],
    keyConcepts: ["Informed Consent", "Confidentiality", "Debriefing", "Institutional Review Board", "Belmont Report", "APA Ethics Code"],
    href: "/wiki/foundations/ethics",
  },
  {
    id: "biological/neuropsychology",
    title: "Neuropsychology",
    description: "Study brain structure, function, and plasticity in relation to behavior.",
    domain: "biological",
    domainTitle: "Biological Bases of Behavior",
    topic: "neuropsychology",
    keywords: ["brain", "neurons", "neuroscience", "plasticity", "cortex"],
    content: "Brain structure and function. Neural plasticity. Hemispheric specialization. Brain imaging.",
    sections: ["Introduction", "Neural Communication", "Brain Structure", "Hemispheric Specialization", "Neuroplasticity", "Brain Imaging Techniques"],
    keyConcepts: ["Neuroplasticity", "Hemispheric Specialization", "Neurotransmitter", "Action Potential", "Cerebral Cortex", "Synapse", "Long-Term Potentiation", "Diaschisis", "BOLD Signal", "Diffuse Axonal Injury"],
    href: "/wiki/biological/neuropsychology",
  },
  {
    id: "biological/sensation-perception",
    title: "Sensation & Perception",
    description: "Explore how we detect, process, and interpret sensory information.",
    domain: "biological",
    domainTitle: "Biological Bases of Behavior",
    topic: "sensation-perception",
    keywords: ["vision", "hearing", "perception", "senses", "attention"],
    content: "Sensory systems. Visual perception. Auditory processing. Bottom-up and top-down processing.",
    sections: ["Introduction", "Sensation", "Perception", "Visual System", "Auditory System", "Other Senses"],
    keyConcepts: ["Threshold", "Just Noticeable Difference", "Transduction", "Retina", "Pitch Perception", "Olfaction", "Gustation", "Gate Control Theory"],
    href: "/wiki/biological/sensation-perception",
  },
  {
    id: "clinical/psychopathology",
    title: "Psychopathology",
    description: "Study abnormal psychology and DSM-5-TR diagnostic categories.",
    domain: "clinical",
    domainTitle: "Clinical & Counseling Psychology",
    topic: "psychopathology",
    keywords: ["DSM-5", "disorders", "abnormal", "diagnosis", "mental illness", "anxiety", "depression"],
    content: "Mental disorders. DSM-5-TR. Anxiety disorders. Mood disorders. Schizophrenia. Personality disorders.",
    sections: ["Introduction", "Definitions of Abnormality", "Anxiety Disorders", "Mood Disorders", "Schizophrenia", "Personality Disorders"],
    keyConcepts: ["DSM-5", "Anxiety", "Depression", "Schizophrenia", "Hallucination", "Delusion", "Obsession", "Compulsion"],
    href: "/wiki/clinical/psychopathology",
  },
  {
    id: "clinical/assessment",
    title: "Psychological Assessment",
    description: "Learn testing, diagnosis, and clinical evaluation methods.",
    domain: "clinical",
    domainTitle: "Clinical & Counseling Psychology",
    topic: "assessment",
    keywords: ["testing", "diagnosis", "MMPI", "WAIS", "interview", "evaluation"],
    content: "Clinical interview. Psychological testing. Intelligence tests. Personality assessment. Neuropsychological testing.",
    sections: ["Introduction", "Types of Assessment", "Intelligence Testing", "Personality Assessment", "Neuropsychological Assessment"],
    keyConcepts: ["Reliability", "Validity", "Standardization", "Norm", "IQ", "Projective Test", "MMPI"],
    href: "/wiki/clinical/assessment",
  },
  {
    id: "clinical/evidence-based-therapies",
    title: "Evidence-Based Psychotherapies",
    description: "Explore CBT, DBT, psychodynamic, and other therapeutic approaches.",
    domain: "clinical",
    domainTitle: "Clinical & Counseling Psychology",
    topic: "evidence-based-therapies",
    keywords: ["CBT", "DBT", "therapy", "psychotherapy", "treatment", "intervention"],
    content: "Cognitive-behavioral therapy. Dialectical behavior therapy. Psychodynamic therapy. ACT. IPT. EMDR.",
    sections: ["Introduction", "Cognitive Behavioral Therapy", "Dialectical Behavior Therapy", "Psychodynamic Therapy", "Other Approaches"],
    keyConcepts: ["CBT", "Cognitive Restructuring", "Exposure Therapy", "Dialectics", "Unconditional Positive Regard", "Insight", "Behavioral Activation"],
    href: "/wiki/clinical/evidence-based-therapies",
  },
  {
    id: "developmental/child-psychology",
    title: "Child Psychology",
    description: "Understand cognitive, social, and emotional development in childhood.",
    domain: "developmental",
    domainTitle: "Developmental Psychology",
    topic: "child-psychology",
    keywords: ["child", "development", "Piaget", "attachment", "cognitive development"],
    content: "Cognitive development. Social development. Emotional development. Piaget. Vygotsky. Attachment theory.",
    sections: ["Introduction", "Physical Development", "Cognitive Development", "Social and Emotional Development", "Language Development", "Parenting and Family Dynamics"],
    keyConcepts: ["Attachment", "Object Permanence", "Zone of Proximal Development", "Scaffolding", "Theory of Mind", "Secure Attachment"],
    href: "/wiki/developmental/child-psychology",
  },
  {
    id: "cognitive/cognitive-psychology",
    title: "Cognitive Psychology",
    description: "Study memory, learning, attention, and problem-solving processes.",
    domain: "cognitive",
    domainTitle: "Cognitive & Affective Aspects",
    topic: "cognitive-psychology",
    keywords: ["memory", "attention", "learning", "thinking", "problem solving"],
    content: "Memory systems. Attention. Learning. Problem solving. Decision making. Language processing.",
    sections: ["Introduction", "Attention", "Perception", "Memory", "Learning", "Language", "Thinking and Reasoning", "Decision Making"],
    keyConcepts: ["Working Memory", "Long-Term Memory", "Attention", "Schema", "Prototype", "Metacognition", "Heuristic", "Framing Effect"],
    href: "/wiki/cognitive/cognitive-psychology",
  },
  {
    id: "social-personality/social-psychology",
    title: "Social Psychology",
    description: "Study group dynamics, prejudice, conformity, and social influence.",
    domain: "social-personality",
    domainTitle: "Social & Personality Psychology",
    topic: "social-psychology",
    keywords: ["social", "group", "conformity", "prejudice", "attitudes"],
    content: "Social influence. Conformity. Obedience. Attitudes. Prejudice. Group dynamics. Attribution.",
    sections: ["Introduction", "Social Cognition", "Social Perception", "Attitudes", "Conformity and Obedience", "Group Influence", "Prosocial Behavior", "Aggression", "Prejudice and Discrimination"],
    keyConcepts: ["Attribution", "Cognitive Dissonance", "Social Norm", "Conformity", "Obedience", "Fundamental Attribution Error", "Self-Serving Bias", "Groupthink"],
    href: "/wiki/social-personality/social-psychology",
  },
  {
    id: "applied/forensic-psychology",
    title: "Forensic Psychology",
    description: "Study criminal behavior and the psychology-legal system interface.",
    domain: "applied",
    domainTitle: "Applied Psychology",
    topic: "forensic-psychology",
    keywords: ["forensic", "criminal", "legal", "court", "crime"],
    content: "Criminal behavior. Legal psychology. Eyewitness testimony. Risk assessment. Competency evaluation.",
    sections: ["Introduction", "Legal System Overview", "Criminal Behavior", "Victimization", "Legal Competency", "Assessment in Legal Contexts", "Ethics in Forensic Psychology"],
    keyConcepts: ["Competency", "Insanity Defense", "Malingering", "Eyewitness Testimony", "Risk Assessment", "Psychopathy"],
    href: "/wiki/applied/forensic-psychology",
  },
  {
    id: "relationships-family/attachment-theory",
    title: "Attachment Theory & Adult Relationships",
    description: "Understand how early attachment experiences shape adult relationships and emotional bonds throughout life.",
    domain: "relationships-family",
    domainTitle: "Relationships & Family",
    topic: "attachment-theory",
    keywords: ["attachment", "relationships", "bonding", "Bowlby", "emotional bonds"],
    content: "Attachment theory. John Bowlby. Internal working models. Secure attachment. Adult relationships.",
    sections: ["Introduction to Attachment Theory", "Bowlby's Attachment Theory", "Infant Attachment Styles", "Adult Attachment", "Attachment and Relationship Dynamics", "Attachment Across the Lifespan"],
    keyConcepts: ["Attachment", "Internal Working Model", "Secure Base", "Safe Haven", "Strange Situation", "Attachment Anxiety", "Attachment Avoidance", "Earned Security", "Demand-Withdraw Pattern", "Disorganized Attachment"],
    href: "/wiki/relationships-family/attachment-theory",
  },
  {
    id: "positive/well-being",
    title: "Well-Being & Happiness",
    description: "Explore the science of well-being, happiness, and flourishing from a psychological perspective.",
    domain: "positive",
    domainTitle: "Positive Psychology",
    topic: "well-being",
    keywords: ["happiness", "well-being", "flourishing", "positive psychology", "Seligman"],
    content: "Well-being. Happiness. Flourishing. PERMA model. Subjective well-being. Eudaimonia.",
    sections: ["Introduction to Well-Being", "Subjective Well-Being", "Eudaimonic Well-Being", "Seligman's PERMA Model", "Determinants of Happiness", "Positive Interventions"],
    keyConcepts: ["Subjective Well-Being", "Eudaimonia", "PERMA Model", "Flow", "Hedonic Adaptation", "Signature Strengths", "Broaden-and-Build Theory", "Self-Determination Theory", "Gratitude", "Flourishing"],
    href: "/wiki/positive/well-being",
  },
  {
    id: "gender-sexuality/gender-psychology",
    title: "Psychology of Gender",
    description: "Explore psychological perspectives on gender, including gender development, identity, and differences.",
    domain: "gender-sexuality",
    domainTitle: "Gender & Sexuality",
    topic: "gender-psychology",
    keywords: ["gender", "identity", "transgender", "gender roles", "sex differences"],
    content: "Gender psychology. Gender identity. Gender development. Transgender. Gender roles.",
    sections: ["Introduction to Gender Psychology", "Sex vs. Gender", "Gender Development", "Gender Similarities and Differences", "Gender Identity Development", "Gender and Mental Health"],
    keyConcepts: ["Gender Identity", "Cisgender", "Transgender", "Non-Binary", "Gender Schema", "Gender Dysphoria", "Gender Similarities Hypothesis", "Stereotype Threat", "Intersex", "Gender-Affirming Care"],
    href: "/wiki/gender-sexuality/gender-psychology",
  },
  {
    id: "consumer-environmental/consumer-behavior",
    title: "Consumer Psychology & Behavior",
    description: "Understand the psychological processes underlying consumer decision-making, persuasion, and marketing psychology.",
    domain: "consumer-environmental",
    domainTitle: "Consumer & Environmental",
    topic: "consumer-behavior",
    keywords: ["consumer", "marketing", "decision-making", "persuasion", "behavioral economics"],
    content: "Consumer psychology. Consumer behavior. Marketing. Decision-making. Persuasion. Behavioral economics.",
    sections: ["Introduction to Consumer Psychology", "Consumer Decision-Making", "Motivation and Needs", "Perception and Attention", "Attitudes and Persuasion", "Social and Cultural Influences", "Behavioral Economics in Marketing"],
    keyConcepts: ["Consumer Decision-Making", "Elaboration Likelihood Model", "Hedonic Consumption", "Sensory Marketing", "Choice Architecture", "Reference Group", "Mental Accounting", "Social Proof", "Loss Aversion", "Brand Community"],
    href: "/wiki/consumer-environmental/consumer-behavior",
  },
  {
    id: "consumer-environmental/environmental-psychology",
    title: "Environmental Psychology",
    description: "Explore the interrelationship between people and their physical environments, including sustainable behavior.",
    domain: "consumer-environmental",
    domainTitle: "Consumer & Environmental",
    topic: "environmental-psychology",
    keywords: ["environment", "restorative", "nature", "sustainability", "built environment"],
    content: "Environmental psychology. Person-environment relationships. Restorative environments. Pro-environmental behavior. Built environment design.",
    sections: ["Introduction to Environmental Psychology", "Person-Environment Relationships", "Environmental Stressors", "Restorative Environments", "Pro-Environmental Behavior", "Built Environment Design", "Climate Change Psychology"],
    keyConcepts: ["Environmental Stressor", "Attention Restoration Theory", "Being Away", "Extent", "Fascination", "Compatibility", "Biophilia", "Place Attachment", "Crowding", "Pro-Environmental Behavior", "Psychological Distance", "Defensible Space", "Eco-Anxiety", "Biophilic Design"],
    href: "/wiki/consumer-environmental/environmental-psychology",
  },
  {
    id: "relationships-family/romantic-relationships",
    title: "Romantic Relationships & Marriage",
    description: "Explore the science of romantic love, relationship maintenance, and factors predicting relationship success.",
    domain: "relationships-family",
    domainTitle: "Relationships & Family",
    topic: "romantic-relationships",
    keywords: ["relationships", "love", "marriage", "communication", "Gottman"],
    content: "Romantic relationships. Love. Marriage. Relationship maintenance. Conflict. Communication. Gottman.",
    sections: ["Introduction to Relationship Science", "Attraction and Relationship Formation", "Love and Its Components", "Relationship Maintenance", "Conflict and Communication", "Relationship Satisfaction and Stability", "Divorce and Relationship Dissolution"],
    keyConcepts: ["Triangular Theory of Love", "Passionate Love", "Companionate Love", "Four Horsemen", "Matching Hypothesis", "Investment Model", "Mere Exposure Effect", "Repair Attempt", "Negative Sentiment Override", "Perpetual Problems"],
    href: "/wiki/relationships-family/romantic-relationships",
  },
  {
    id: "relationships-family/parenting-psychology",
    title: "Parenting Psychology",
    description: "Understand the psychology of parenting, including parenting styles, child development, and parent-child relationships.",
    domain: "relationships-family",
    domainTitle: "Relationships & Family",
    topic: "parenting-psychology",
    keywords: ["parenting", "children", "discipline", "attachment", "Baumrind"],
    content: "Parenting. Parenting styles. Child development. Parent-child relationships. Discipline. Attachment.",
    sections: ["Introduction to Parenting Psychology", "Parenting Styles", "Parent-Child Attachment", "Discipline and Behavior Management", "Parenting Across Contexts", "Parent Well-Being and Self-Care"],
    keyConcepts: ["Authoritative Parenting", "Sensitive Responsiveness", "Induction", "Parenting Stress", "Intergenerational Transmission", "Psychological Control", "Co-parenting", "Earned Security"],
    href: "/wiki/relationships-family/parenting-psychology",
  },
  {
    id: "positive/character-strengths",
    title: "Character Strengths & Virtues",
    description: "Discover the science of human strengths and how to cultivate virtuous character.",
    domain: "positive",
    domainTitle: "Positive Psychology",
    topic: "character-strengths",
    keywords: ["character", "strengths", "virtues", "VIA", "signature strengths"],
    content: "Character strengths. Virtues. VIA Classification. Signature strengths. Strengths-based interventions.",
    sections: ["Introduction to Character Strengths", "The VIA Classification", "Signature Strengths", "Strengths-Based Interventions", "Research Evidence"],
    keyConcepts: ["Character Strength", "VIA Classification", "Signature Strength", "Virtue", "Golden Mean", "Strength Overuse", "Strengths-Spotting", "Job Crafting"],
    href: "/wiki/positive/character-strengths",
  },
  {
    id: "positive/resilience",
    title: "Resilience & Post-Traumatic Growth",
    description: "Understand psychological resilience and the potential for growth following adversity.",
    domain: "positive",
    domainTitle: "Positive Psychology",
    topic: "resilience",
    keywords: ["resilience", "trauma", "growth", "coping", "adversity"],
    content: "Resilience. Post-traumatic growth. Coping. Adversity. Protective factors. Stress inoculation.",
    sections: ["Introduction to Resilience", "Understanding Resilience", "Factors Promoting Resilience", "Post-Traumatic Growth", "Building Resilience"],
    keyConcepts: ["Resilience", "Post-Traumatic Growth", "Protective Factor", "Stress Inoculation", "Assumptive World", "Deliberate Rumination", "Emotional Regulation", "Hardiness"],
    href: "/wiki/positive/resilience",
  },
  {
    id: "gender-sexuality/human-sexuality",
    title: "Psychology of Human Sexuality",
    description: "Explore the psychology of sexual development, orientation, behavior, and well-being across the lifespan.",
    domain: "gender-sexuality",
    domainTitle: "Gender & Sexuality",
    topic: "human-sexuality",
    keywords: ["sexuality", "sexual orientation", "LGBTQ", "sexual health", "Kinsey"],
    content: "Human sexuality. Sexual orientation. Sexual development. Sexual behavior. LGBTQ+ mental health. Sexual well-being.",
    sections: ["Introduction to Sexuality Psychology", "Sexual Development", "Sexual Orientation", "Sexual Response and Behavior", "Sexual Well-Being", "LGBTQ+ Mental Health"],
    keyConcepts: ["Sexual Orientation", "Sexual Response Cycle", "Minority Stress", "Consent", "Kinsey Scale", "Sexual Dysfunction", "Asexuality", "Affirmative Therapy", "Sexual Well-Being", "Internalized Stigma"],
    href: "/wiki/gender-sexuality/human-sexuality",
  },
];

const fuseOptions = {
  keys: [
    { name: "title", weight: 0.4 },
    { name: "keyConcepts", weight: 0.3 }, // Key concepts are highly searchable
    { name: "sections", weight: 0.2 }, // Section titles
    { name: "description", weight: 0.15 },
    { name: "keywords", weight: 0.1 },
    { name: "content", weight: 0.05 },
    { name: "domainTitle", weight: 0.05 },
  ],
  threshold: 0.3,
  includeScore: true,
  includeMatches: true,
};

const fuse = new Fuse(searchIndex, fuseOptions);

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const query = searchParams.get("q") || "";
  const limit = parseInt(searchParams.get("limit") || "10", 10);

  if (!query.trim()) {
    return NextResponse.json({ results: [], query: "" });
  }

  const results = fuse.search(query, { limit }).map((result) => ({
    id: result.item.id,
    title: result.item.title,
    description: result.item.description,
    domain: result.item.domain,
    domainTitle: result.item.domainTitle,
    topic: result.item.topic,
    href: result.item.href,
    score: result.score,
    sections: result.item.sections,
    keyConcepts: result.item.keyConcepts,
  }));

  return NextResponse.json({ results, query });
}
